### ISSUE TITLE
[Analysis] Clarify Cummulative Hospitalization

### ISSUE THREAD

**Issue by BicaAnamaria** [BicaAnamaria/EpidemicSimulator#64]
Clarify Cummulative Hospitalization

**Comment by discoleo** [comment]
There are 2 major indicators:

1. Total number of patients in hospitals on day i;
2. Total number of patients that are hospitalized on day i;

## Patients in Hosptial
This is the H compartment.

## daily Hospitalizations
These are computed from Hcum.
