### ISSUE TITLE
[Help] Reactive page

### ISSUE THREAD

**Issue by BicaAnamaria** [BicaAnamaria/EpidemicSimulator#83]
TODO: update/ how to update Help page in Server

**Comment by discoleo** [comment]
# Reactive page

- UI: use uiOutput;
- Server: use renderUI;

Note:
- this is only a conversion to "proper" shiny code;
- the existing functionality is re-implemented using proper code;
- the full functionality will follow afterwards;

## UI.R
- much simplified UI code;

```
tabPanel("Help",
    uiOutput("HelpUI")
)
```

## Server.R
- the helpEpidem() is moved in the Server code;

```
  ### Help
  output$HelpUI <- renderUI({
    helpEpidem();
  })
```
