### ISSUE TITLE
Legend colors

### ISSUE THREAD

**Issue by BicaAnamaria** [BicaAnamaria/EpidemicSimulator#84]
TODO: different types of lines or consistent colors

**Comment by discoleo** [comment]
## Color Hcum

Use a pale blue colour: Hcum = "#9d9dF0";
- Hcum is in general a less important variable: can be a pale colour;
- blue will not interfere with the other variables;

## Symbol in Legend

Change the symbol to filled circle: pch = 19.
```
### Add legend
  if(plot.legend) {
    legend(legend.xy[1], legend.xy[2], legend.lbl,
           pch = 19, col = col, bty = "n")
  }
```
