### ISSUE TITLE
Hosp + Death Cumulative for Analysis

### ISSUE THREAD

**Issue by BicaAnamaria** [BicaAnamaria/EpidemicSimulator#97]

**Comment by discoleo** [comment]
# Analysis: Basic Statistics

## UI
- add another table;

```
                  tabPanel("Analysis",
                           tableOutput("doStatistics"),
                           tableOutput("doBasicStatistics"),
                           downloadButton("downloadData", "Download")
                  ),
```

## Server
- implement the function doBasicStatistics: similar to doStatistics;

```
  output$doBasicStatistics = renderTable({
    summaryBasicSIR(values$outData);
  }, align = c('c'))
```

## Analysis
- implement the actual function summaryBasicSIR:

Note:
- the functions doStatistics & summarySIR could be renamed to doAnalysis and analyseSIR;
